#pragma checksum ".\Bind.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f67ecaecec8af8c164e7ab338f5fe73f8f8068c1"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 1 ".\Bind.razor"
    using Sandbox.UI;
    public partial class Bind : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "f67ecaecec8af8c164e7ab338f5fe73f8f8068c1";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\Bind.razor", 4, 0 );
            __builder.OpenElement( 0, "div", null );
            {
                __builder.AddLocation( ".\\Bind.razor", 5, 4 );
                #line 5 ".\Bind.razor"
                __builder.OpenElement<Panel>( 1 , null );
                {
                    #line 5 ".\Bind.razor"
                    __builder.AddReferenceCapture( 2, TargetPanel, ( _v ) => { TargetPanel = _v; });
                    #line 5 ".\Bind.razor"
                    __builder.AddBind( 3, "ElementName", () => PanelName, ( v ) => PanelName = v );
                }
                __builder.CloseElement();
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
        #line 9 ".\Bind.razor"
 
    public Panel TargetPanel{ get; set; }
    public string PanelName { get; set; } = "Poops";
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
