#pragma checksum ".\ComponentUser.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f728d0bd9f5a6c783b98f815451692d5c200dc20"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\ComponentUser.razor"
    using System.Diagnostics;
    public partial class ComponentUser : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "f728d0bd9f5a6c783b98f815451692d5c200dc20";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\ComponentUser.razor", 4, 0 );
            #line 4 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 0 , null );
            {
                #line 4 ".\ComponentUser.razor"
                {
                    var __v = (
                    "One");__builder.AddAttribute<Icon>( 1, __v, ( _o ) => _o.Title = __v );
                }
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\ComponentUser.razor", 4, 25 );
            __builder.AddMarkupContent( 2, "\r\n" );
            __builder.AddLocation( ".\\ComponentUser.razor", 5, 0 );
            #line 5 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 3 , null );
            {
                #line 5 ".\ComponentUser.razor"
                {
                    var __v = (
                    Two);__builder.AddAttribute<Icon>( 4, __v, ( _o ) => _o.Title = __v );
                }
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\ComponentUser.razor", 5, 24 );
            __builder.AddMarkupContent( 5, "\r\n" );
            __builder.AddLocation( ".\\ComponentUser.razor", 6, 0 );
            #line 6 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 6 , null );
            {
                #line 6 ".\ComponentUser.razor"
                {
                    var __v = (
                    "Three");__builder.AddAttribute<Icon>( 7, __v, ( _o ) => _o.Title = __v );
                }
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\ComponentUser.razor", 6, 27 );
            __builder.AddMarkupContent( 8, "\r\n" );
            __builder.AddLocation( ".\\ComponentUser.razor", 7, 0 );
            #line 7 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 9 , null );
            {
                #line 7 ".\ComponentUser.razor"
                {
                    var __v = (
                    "Four");__builder.AddAttribute<Icon>( 10, __v, ( _o ) => _o.Title = __v );
                }
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\ComponentUser.razor", 7, 26 );
            __builder.AddMarkupContent( 11, "\r\n" );
            __builder.AddLocation( ".\\ComponentUser.razor", 8, 0 );
            #line 8 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 12 , null );
            {
                #line 8 ".\ComponentUser.razor"
                {
                    var __v = (
                    "Nice");__builder.AddAttribute<Icon>( 13, __v, ( _o ) => _o.Title = __v );
                }
                #line 8 ".\ComponentUser.razor"
                __builder.AddAttribute<Icon>( 14, ( o ) => {  o.OnSomethingSomething = OnCallback; } );
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\ComponentUser.razor", 8, 60 );
            __builder.AddMarkupContent( 15, "\r\n" );
            __builder.AddLocation( ".\\ComponentUser.razor", 9, 0 );
            #line 9 ".\ComponentUser.razor"
            __builder.OpenElement<Icon>( 16 , null );
            {
                #line 9 ".\ComponentUser.razor"
                {
                    var __v = (
                    "Nice");__builder.AddAttribute<Icon>( 17, __v, ( _o ) => _o.Title = __v );
                }
                #line 9 ".\ComponentUser.razor"
                __builder.AddAttribute<Icon>( 18, ( o ) => {  o.OnSomethingSomething = () => OnCallback() ; } );
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
        #line 12 ".\ComponentUser.razor"
 
    public string Two = "Two";

    public int CallbackCalls = 0;

    public void OnCallback()
    {
        CallbackCalls++;
    }
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
