#pragma checksum ".\Icon.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c55dd6d05669637366fa28680893ad9957c1eba1"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    public partial class Icon : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "c55dd6d05669637366fa28680893ad9957c1eba1";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\Icon.razor", 3, 0 );
            __builder.OpenElement( 0, "div", null );
            {
                __builder.AddLocation( ".\\Icon.razor", 3, 5 );
                __builder.AddMarkupContent( 1, "\r\n    The Title Is " );
                #line 4 ".\Icon.razor"
                __builder.AddContent(2, Title);
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
        #line 8 ".\Icon.razor"
 
    public string Title { get; set; }

    public System.Action OnSomethingSomething{ get; set; }

    public void TriggerCallback()
    {
        OnSomethingSomething?.Invoke();
    }
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
