#pragma checksum ".\NestedPanel.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2070eb215a4ddc57e2d5f71efbf9fdd7ba462adf"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    public partial class NestedPanel : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "2070eb215a4ddc57e2d5f71efbf9fdd7ba462adf";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\NestedPanel.razor", 3, 0 );
            __builder.OpenElement( 0, "div", null );
            {
                __builder.AddLocation( ".\\NestedPanel.razor", 4, 1 );
                __builder.OpenElement( 1, "div", null );
                {
                    #line 5 ".\NestedPanel.razor"
                    __builder.AddContent(2, this);
                    __builder.AddLocation( ".\\NestedPanel.razor", 5, 8 );
                    __builder.AddMarkupContent( 3, " Nested content\r\n\t" );
                }
                __builder.CloseElement();
            }
            __builder.CloseElement();
            __builder.AddLocation( ".\\NestedPanel.razor", 7, 6 );
            __builder.AddMarkupContent( 4, "\r\n\r\n" );
            __builder.AddLocation( ".\\NestedPanel.razor", 9, 0 );
            __builder.AddMarkupContent( 5, "<div><div>\r\n\t\tNested markup\r\n\t</div></div>" );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
