#pragma checksum ".\RecursivePanel.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8d9a632e46d6a50591c9a57d08f6d7e0d910d1aa"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\RecursivePanel.razor"
    using System.Diagnostics;
    #line 3 ".\RecursivePanel.razor"
    using Sandbox.UI;
    public partial class RecursivePanel : Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "8d9a632e46d6a50591c9a57d08f6d7e0d910d1aa";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\RecursivePanel.razor", 6, 0 );
            __builder.OpenElement( 0, "root", null );
            {
                __builder.AddLocation( ".\\RecursivePanel.razor", 7, 1 );
                __builder.OpenElement( 1, "div", null );
                {
                    #line 7 ".\RecursivePanel.razor"
                    __builder.AddAttribute(2, "class", "recursive-panel-parent");
                    __builder.AddLocation( ".\\RecursivePanel.razor", 8, 2 );
                    // Tried to include recursively here
                    throw new System.Exception("Tried to include element 'RecursivePanel' recursively!");
                }
                __builder.CloseElement();
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
