#pragma checksum ".\RefAttribute.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7f32017db6a19ad18b8704822ef9f9a846f3ace0"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\RefAttribute.razor"
    using System.Diagnostics;
    #line 3 ".\RefAttribute.razor"
    using Sandbox.UI;
    public partial class RefAttribute : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "7f32017db6a19ad18b8704822ef9f9a846f3ace0";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            #line 5 ".\RefAttribute.razor"
 if ( ShowFirstElement)
{
            __builder.AddLocation( ".\\RefAttribute.razor", 7, 4 );
            __builder.OpenElement( 0, "div", null );
            {
                #line 7 ".\RefAttribute.razor"
                __builder.AddReferenceCapture( 1, MyReferencedElement, ( _v ) => { MyReferencedElement = _v; });
                #line 7 ".\RefAttribute.razor"
                __builder.AddContent(2, this);
            }
            __builder.CloseElement();
            #line 8 ".\RefAttribute.razor"
            }
            __builder.AddLocation( ".\\RefAttribute.razor", 9, 0 );
            __builder.OpenElement( 3, "div", null );
            {
                #line 9 ".\RefAttribute.razor"
                __builder.AddReferenceCapture( 4, MyReferencedMarkup, ( _v ) => { MyReferencedMarkup = _v; });
                __builder.AddContent( 5, "markup content" );
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
        #line 12 ".\RefAttribute.razor"
 
    public Panel MyReferencedElement{ get; set; }
    public Panel MyReferencedMarkup{ get; set; }
    public bool ShowFirstElement { get; set; } = true;
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
