#pragma checksum ".\RootPanel.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a5e88da763a73587d4ac404be1ed639abc5f3251"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\RootPanel.razor"
    using System.Diagnostics;
    public partial class RootPanel : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "a5e88da763a73587d4ac404be1ed639abc5f3251";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\RootPanel.razor", 4, 0 );
            __builder.OpenElement( 0, "root", null );
            {
                #line 4 ".\RootPanel.razor"
                __builder.AddAttribute(1, "style", "background-color: red;");
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
