#pragma checksum ".\SiblingOrder.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "650befd0db82ba6f414aa079a0d57908a27515ef"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\SiblingOrder.razor"
    using System.Diagnostics;
    #line 3 ".\SiblingOrder.razor"
    using Sandbox.UI;
    public partial class SiblingOrder : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "650befd0db82ba6f414aa079a0d57908a27515ef";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            #line 5 ".\SiblingOrder.razor"
 if (ShowFirstItem)
{
            __builder.AddLocation( ".\\SiblingOrder.razor", 7, 4 );
            __builder.OpenElement( 0, "one", null );
            {
                #line 7 ".\SiblingOrder.razor"
                __builder.AddReferenceCapture( 1, One, ( _v ) => { One = _v; });
            }
            __builder.CloseElement();
            #line 8 ".\SiblingOrder.razor"
            }
            #line 10 ".\SiblingOrder.razor"
 if (ShowMiddleItem)
{
            __builder.AddLocation( ".\\SiblingOrder.razor", 12, 4 );
            __builder.AddMarkupContent( 2, "<two></two>" );
            #line 13 ".\SiblingOrder.razor"
            }
            __builder.AddLocation( ".\\SiblingOrder.razor", 15, 0 );
            __builder.OpenElement( 3, "three", null );
            {
                #line 15 ".\SiblingOrder.razor"
                __builder.AddReferenceCapture( 4, Three, ( _v ) => { Three = _v; });
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
        #line 18 ".\SiblingOrder.razor"
 
    public bool ShowFirstItem { get; set; }
    public bool ShowMiddleItem { get; set; }

    public Panel One { get; set; }
    public Panel Three { get; set; }
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
