#pragma checksum ".\SimpleWithContent.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "83fd1745fe1f7de15f6a1005ed9811417f78bcbb"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    #line 2 ".\SimpleWithContent.razor"
    using System.Diagnostics;
    public partial class SimpleWithContent : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "83fd1745fe1f7de15f6a1005ed9811417f78bcbb";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\SimpleWithContent.razor", 4, 0 );
            __builder.OpenElement( 0, "div", null );
            {
                __builder.AddContent( 1, "this is a content element because it has " );
                #line 4 ".\SimpleWithContent.razor"
                __builder.AddContent(2, this);
                __builder.AddContent( 3, " - which is dynamic content" );
            }
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
