#pragma checksum ".\SimpleWithMarkup.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "07a22d34d0d4bef0ed2e86b88fb383abc261c777"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0162
namespace TestComponents
{
    #line hidden
    public partial class SimpleWithMarkup : global::Sandbox.UI.Panel
    {
        // Make sure everyone knows that we have a render tree
        // (this is an optimization so we have a quick and definite way to check)
        protected override string GetRenderTreeChecksum() => "07a22d34d0d4bef0ed2e86b88fb383abc261c777";

        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddLocation( ".\\SimpleWithMarkup.razor", 3, 0 );
            __builder.AddMarkupContent( 0, "<div style=\"background-color: red;\">This is a markup element - it has no dynamic content</div>" );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 0162
#pragma warning restore 1591
